### ISSUE TITLE
CJK characters

### ISSUE THREAD

**Issue by lrussell887** [mmtrt/foobar2000_AppImage#2]
![Screenshot_20230105_070121](https://user-images.githubusercontent.com/7494773/210782210-41a61afd-80ad-4943-a193-0681c7249178.png)

CJK characters display as squares, is there any way to fix this?

I'm using the [foobar2000-1.6.14-aarch64](https://github.com/mmtrt/foobar2000_AppImage/releases/download/stable-box86/foobar2000-1.6.14-aarch64.AppImage) AppImage on Manjaro-ARM.

**Comment by mmtrt** [comment]
you can change font from app setting.

![Screenshot_20230107_114945](https://user-images.githubusercontent.com/2322598/211135370-76a69840-4897-469f-8cac-896c11d0df16.png)
